pdf_analyzer_task:
  description: >
      Extract and Analyze the PDF content in path {pdf_path} and identify:
        1. Key concepts and topics
        2. Important facts and definitions
        3. Learning objectives
        4. Complex ideas that need to be tested
        
      Provide a structured summary of the content that can be used to generate quizzes.
      
      The output should be a JSON object with:
      - key_concepts: List of main concepts and topics
      - important_facts: List of important facts and definitions
      - learning_objectives: List of learning objectives
      - complex_topics: List of complex topics that need testing
      - summary: A brief summary of the content
  expected_output: >
      A structured summary of the content that can be used to generate quizzes.
  agent: pdf_analyzer 



quiz_generator_task:
  description: >
      Using the analysis provided, create a comprehensive quiz that includes:
        1. Multiple choice questions
        2. True/False questions
        3. Short answer questions
            
        For each question:
        - Include the correct answer
        - Provide an explanation for the answer
        - Indicate the difficulty level
        
        The output should be a JSON object with a list of questions, where each question has:
        - question: The question text
        - type: One of "multiple_choice", "true_false", or "short_answer"
        - correct_answer: The correct answer
        - explanation: Explanation of the answer
        - difficulty: The difficulty level
        - options: List of options (only for multiple_choice questions)

  expected_output: >
      A comprehensive quiz that includes multiple choice questions, true/false questions, and short answer questions.
  agent: quiz_generator